### ISSUE TITLE
LED color codes.

### ISSUE THREAD

**Issue by kciszewski** [KanoComputing/community-sdk#14]
I got "example_pixel_kit_stream_frame.py" running. It would be helpful to know what the six digit hex codes are for the possible colors of the leds.

**Comment by murilopolese** [comment]
Hey, @kciszewski!

The six digit codes are precisely what you said: Hexadecimal codes for colors. It's a very common way to describe colors specially on web technologies. You will find [a lot of information about it on the internet](https://duckduckgo.com/?q=hexadecimal+colors).

Does that answer your question?

**Comment by kciszewski** [comment]
Since I don't have the part number of the LEDs, probably not.

--------------------------------------------
On Mon, 11/12/18, Murilo Polese <notifications@github.com> wrote:

 Subject: Re: [KanoComputing/community-sdk] LED color codes. (#14)
 To: "KanoComputing/community-sdk" <community-sdk@noreply.github.com>
 Cc: "kciszewski" <kenski@swbell.net>, "Mention" <mention@noreply.github.com>
 Date: Monday, November 12, 2018, 12:58 PM
 
 Hey, @kciszewski!
 The six digit codes are precisely what you said:
 Hexadecimal codes for colors. It's a very common way to
 describe colors specially on web technologies. You will find
 a lot of
 information about it on the internet.
 Does that answer your question?
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by murilopolese** [comment]
> I got "example_pixel_kit_stream_frame.py" running.

Cool!

> It would be helpful to know what the six digit hex codes are

Hexadecimal color code. That is what the six digit codes are. The two first for "red", followed by two digits for "blue" and the last two digits are for "green". 

If you want to know more about the color conversion from the hexadecimal to the format the firmware accepts (base64 encoded rgb565 colors), [check this part of the code](https://github.com/KanoComputing/community-sdk/blob/python/communitysdk/retailpixelkit.py#L25-L33).

> for the possible colors of the leds

That is a very complicated question to make and I see no simple way to answer this. Are you being blocked to create something by this question or is that more of a curiosity? In the first case, can you explain what are you trying to do? If you are just curious I invite you to run a few tests and read the source code to find an approximation to the answer. If you do that, please share your results because I don't have it!

> Since I don't have the part number of the LEDs, probably not.

So what you want is the part number for the LED? I'm not sure if I can provide that information as it's outside of the boundaries of the `communitysdk` :T 

If that doesn't answer your questions, could you talk a bit more about it? Maybe you have a new questions or want to rephrase it?

**Comment by kciszewski** [comment]
I'm trying to get programmable control of individual and groups of LEDS.

As I look around the Web, I keep finding different things.

Let's try this a different way.  I found kano-pixel-kit-pixel32_docs on Git Hub, but am not sure how to use it.  This page looks like it contains parts of python scripts.


--------------------------------------------
On Mon, 11/12/18, Murilo Polese <notifications@github.com> wrote:

 Subject: Re: [KanoComputing/community-sdk] LED color codes. (#14)
 To: "KanoComputing/community-sdk" <community-sdk@noreply.github.com>
 Cc: "kciszewski" <kenski@swbell.net>, "Mention" <mention@noreply.github.com>
 Date: Monday, November 12, 2018, 4:12 PM
 
 
 I got "example_pixel_kit_stream_frame.py"
 running.
 
 Cool!
 
 
 It would be helpful to know what the six digit hex codes
 are
 
 Hexadecimal color code. That is what the six digit codes
 are. The two first for "red", followed by two
 digits for "blue" and the last two digits are for
 "green".
 
 If you want to know more about the color conversion from
 the hexadecimal to the format the firmware accepts (base64
 encoded rgb565 colors), check
 this part of the code.
 
 for the possible colors of the leds
 
 That is a very complicated question to make and I see no
 simple way to answer this. Are you being blocked to create
 something by this question or is that more of a curiosity?
 In the first case, can you explain what are you trying to
 do? If you are just curious I invite you to run a few tests
 and read the source code to find an approximation to the
 answer. If you do that, please share your results because I
 don't have it!
 
 
 Since I don't have the part number of the LEDs,
 probably not.
 
 So what you want is the part number for the LED? I'm not
 sure if I can provide that information as it's outside
 of the boundaries of the communitysdk :T
 
 If that doesn't answer your questions, could you talk
 a bit more about it? Maybe you have a new questions or want
 to rephrase it?
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by murilopolese** [comment]
Hey @kciszewski !

That is indeed a very different question from the original one! xD

Let's do this step by step:

1. Is the question from this issue answered: About the HEX colors? Or do you believe that question is no longer relevant? If so, would you mind closing this issue and opening another one more specific to what you want to know? This is just an organisation thing so people from the future can find answers to their questions easily :)
1. You can set individual LEDs using the `communitysdk` but as we speak there is no dedicated method to do it. When we stream the frame to the board we send 128 color values: one for each LED. Those values are a linear representation of a two dimensional matrix and to set, for example, the pixel on the coordinate `x = 2` and `y = 4` all you need to do is to calculate: `ledIndex = (x * 16) + y`. Perhaps [this feature request I just created](https://github.com/KanoComputing/community-sdk/issues/15) will be more what you are looking for?
1. The `communitysdk` and the `pixel32` are two completely different projects with completely different approaches. I believe there is relevance for both and you might want to review the [`communitysdk` goals and roadmap](https://github.com/KanoComputing/community-sdk/wiki/Goals-and-Roadmap) and the [pixel32 readme](https://github.com/murilopolese/kano-pixel-kit-pixel32) to decide which one is the best for your projects.

**Comment by murilopolese** [comment]
Hey, @kciszewski! Does my reply answer your question? 

I opened a [new feature request](https://github.com/KanoComputing/community-sdk/issues/15) for an easier way to set colors on individual LEDs so I wonder if we could close this one :)

**Comment by kciszewski** [comment]
Close this one.
