### ISSUE TITLE
Python - Export to Pixel Kit

### ISSUE THREAD

**Issue by bi3mer** [KanoComputing/community-sdk#17]
Is there anyway to export our Python code to the Pixel Kit instead of having to run it from our computer every time? If this is not possible with Python, can this be accomplished with the Javascript version? I saw #13 but didn't find it super clear.

Thanks in advance.

**Comment by dcasati** [comment]
same question here. is this possible  at all ? @murilopolese

**Comment by murilopolese** [comment]
Hello there!! :B

*Short answer*: No.

With the official Kano firmware you’ll always be streaming data from your
computer to the PixelKit (ridiculous, I know). You can “save animations”
but you will be better off with the Kano App
<https://kano.me/us/landing/app> for that.

*Long answer*: Yes. Replace the Kano Firmware with either MicroPython
<https://micropython.org/download/esp32/> or Espruino
<https://www.espruino.com/Download> firmwares and you’ll have either python
or javascript running on your PixelKit. This is probably the best thing you
can do. (I recommend MicroPython)

The PixelKit is an *ESP32* board and the *“neopixel” array is hooked on pin
4*. This should be all the info you need to hack your way!

If you are completely lost, I recommend my other attempt to give PixelKit
some life beyond Kano App with Pixel32 firmware
<https://murilopolese.github.io/kano-pixel-kit-pixel32-docs/>. There is an
Instructable
<https://www.instructables.com/id/Flashing-MicroPython-on-Kano-Pixel-Kit/>
on how to replace and recover the firmware and a few simple tutorials
<https://murilopolese.github.io/kano-pixel-kit-pixel32-docs/tutorials>.
