### ISSUE TITLE
Pixel Kit Physical settings?

### ISSUE THREAD

**Issue by netmanchris** [KanoComputing/community-sdk#9]
Trying to connect to the Pixel kit and use the *example_list_connected_devices.py* script. The script is functioning properly, but is unable to detect the Pixel kit itself. 

` 
Found 0 devices
Found 0 Motion Sensor Kits
Found 0 Pixel Kits`

I'm assuming that there's some physical settings on the device that must be set to expose it for control from the serial port properly but I've been unable to find them. 

If anyone's got the cheat sheet please post. 

- Yes - I've forked the WIKI and will document and submit PR when I figure this out.  :)

**Comment by murilopolese** [comment]
I don't think there should be any extra physical setting on the device. Perhaps missing drivers? https://github.com/KanoComputing/community-sdk/issues/8

**Comment by murilopolese** [comment]
Hey, @netmanchris ! Do you think this one is closed as well? :)

**Comment by netmanchris** [comment]
Closing.
